'use strict';
// Roster. `look` drives the chibi renderer (draw.js); `style` picks normal-attack poses;
// s1/s2/su are the G/H/J moves (templates built in moves.js).
const ROSTER = [
  {
    id: 'luffy', name: 'LUFFY', full: 'Monkey D. Luffy', group: 0, style: 'punch', elem: 'rubber',
    quote: "I'm gonna be King of the Pirates!",
    look: { skin: '#f7c99e', hair: { style: 'spiky', color: '#1a1a1a' }, hat: { type: 'straw' }, eyes: 'normal', mouth: 'grin', extras: ['scarEye'], top: { style: 'vest', color: '#d32f2f' }, sleeves: 'short', sash: '#f2c94c', bottom: { style: 'shorts', color: '#2563b0' }, shoes: '#a1887f' },
    s1: { type: 'stretch', name: 'Gum-Gum Pistol', elem: 'rubber', dmg: 75, range: 460 },
    s2: { type: 'transform', name: 'Gear 5', form: 'luffy_g5', elem: 'rubber', dur: 480 },
    su: { type: 'gatling', name: 'Gum-Gum Jet Gatling', maxName: 'Gum-Gum Kong Gatling', elem: 'rubber', g5: { type: 'bajrang', name: 'Gum-Gum Bajrang Gun', maxName: 'Gear 5 MAX: Bajrang Gun', elem: 'rubber', power: 1.15 }, power: 1.1 },
  },
  {
    id: 'zoro', name: 'ZORO', full: 'Roronoa Zoro', group: 0, style: 'sword', elem: 'slash',
    quote: 'Nothing happened.',
    look: { skin: '#e8b088', hair: { style: 'short', color: '#3aa34f' }, eyes: 'sharp', mouth: 'smirk', extras: ['earrings', 'scarEye2'], top: { style: 'robe', color: '#2e7d4f', color2: '#1b5e20' }, sleeves: 'short', sash: '#b71c1c', bottom: { style: 'pants', color: '#1f3b2a' }, shoes: '#222', weapon: 'katana3' },
    s1: { type: 'proj', name: '36 Pound Cannon', elem: 'slash', sprite: 'slash', art: 'slash_blue', artK: 3.8, dmg: 70, speed: 13, r: 44 },
    s2: { type: 'rush', style: 'through', name: 'Onigiri', elem: 'slash', dmg: 95 },
    su: { type: 'asura', name: 'Asura: Nine Sword Flash', elem: 'slash' },
  },
  {
    id: 'nami', name: 'NAMI', full: 'Nami', group: 0, style: 'sword', elem: 'lightning',
    quote: "Thunder beats everything! Now pay up!",
    look: { skin: '#f7c99e', hair: { style: 'long', color: '#ff8a2b' }, eyes: 'fem', mouth: 'smile', top: { style: 'stripes', color: '#4fc3f7', color2: '#ffffff' }, sleeves: 'none', bottom: { style: 'pants', color: '#4b6ea8' }, shoes: '#e57373', weapon: 'staff' },
    s1: { type: 'pillar', name: 'Thunderbolt Tempo', elem: 'lightning', art: 'lightning', cloud: true, dmg: 85 },
    s2: { type: 'proj', name: 'Cyclone Tempo', elem: 'water', sprite: 'tornado', art: 'cyclone', artK: 4.2, dmg: 75, speed: 8, r: 46, hits: 3 },
    su: { type: 'zeusbreeze', name: 'Zeus Breeze Tempo', elem: 'lightning' },
  },
  {
    id: 'usopp', name: 'USOPP', full: 'Usopp', group: 0, style: 'punch', elem: 'fire',
    quote: 'The great Captain Usopp wins again!',
    look: { skin: '#9c6639', hair: { style: 'curlylong', color: '#1a1a1a' }, eyes: 'normal', mouth: 'grin', extras: ['longnose', 'goggles'], top: { style: 'overalls', color: '#f5f5f5', color2: '#7b5a2e' }, sleeves: 'none', bottom: { style: 'pants', color: '#7b5a2e' }, shoes: '#5d4037', weapon: 'slingshot' },
    s1: { type: 'proj', name: 'Lead Star', elem: 'punch', sprite: 'bullet', dmg: 55, speed: 18, r: 14 },
    s2: { type: 'pillar', name: 'Pop Green: Trampolia', elem: 'plant', art: 'trampolia', dmg: 80 },
    su: { type: 'bigproj', name: 'Fire Bird Star', elem: 'fire', sprite: 'bird', art: 'phoenix', artK: 3.4, r: 100, speed: 7, power: 1.4 },
  },
  {
    id: 'sanji', name: 'SANJI', full: 'Vinsmoke Sanji', group: 0, style: 'kick', elem: 'fire',
    quote: 'A cook never lets anyone go hungry... or win!',
    look: { skin: '#f7d2ad', hair: { style: 'swept', color: '#ffd54f' }, eyes: 'normal', mouth: 'smirk', extras: ['curlybrow'], top: { style: 'suit', color: '#1c1c28', color2: '#4fc3f7' }, sleeves: 'long', bottom: { style: 'pants', color: '#1c1c28' }, shoes: '#111' },
    s1: { type: 'rush', style: 'spin', name: 'Devil Leg', elem: 'fire', dmg: 90 },
    s2: { type: 'upper', style: 'skywalk', name: 'Sky Walk', elem: 'fire', dmg: 85 },
    su: { type: 'ifrit', name: 'Ifrit Leg', elem: 'bluefire', power: 1.1 },
  },
  {
    id: 'chopper', name: 'CHOPPER', full: 'Tony Tony Chopper', group: 0, style: 'punch', elem: 'punch',
    quote: "Saying nice things won't make me happy, you jerk! Hehe!",
    look: { skin: '#a0673f', scale: 0.8, build: 'kid', hair: { style: 'fur', color: '#8d5a3b' }, hat: { type: 'tophat', color: '#f06292', color2: '#ffffff', cross: true }, eyes: 'big', mouth: 'smile', extras: ['antlers', 'bluenose'], top: { style: 'shirtless' }, sleeves: 'none', bottom: { style: 'shorts', color: '#e57373' }, shoes: '#5d3a24' },
    s1: { type: 'rush', style: 'charge', name: 'Horn Point', elem: 'punch', dmg: 85 },
    s2: { type: 'upper', name: 'Heavy Gong', elem: 'punch', dmg: 90 },
    su: { type: 'monster', name: 'Monster Point Rampage', elem: 'punch', power: 1.1 },
  },
  {
    id: 'robin', name: 'ROBIN', full: 'Nico Robin', group: 0, style: 'kick', elem: 'flower',
    quote: 'A hundred flowers... that was fun.',
    look: { skin: '#ecc19b', hair: { style: 'long', color: '#1b1b2f', bangs: true }, eyes: 'fem', mouth: 'calm', top: { style: 'shirt', color: '#7e57c2' }, sleeves: 'long', bottom: { style: 'pants', color: '#2c2c54' }, shoes: '#222' },
    s1: { type: 'pillar', name: 'Hundred Flowers: Clutch', elem: 'flower', hands: true, dmg: 85 },
    s2: { type: 'rush', style: 'demonio', name: 'Demon Flowers', elem: 'flower', dmg: 90 },
    su: { type: 'mano', name: 'Giant Hand', elem: 'flower' },
  },
  {
    id: 'franky', name: 'FRANKY', full: 'Franky', group: 0, style: 'punch', elem: 'laser',
    quote: "I'm SUUUPER!",
    look: { skin: '#f2c099', scale: 1.12, build: 'big', hair: { style: 'pompadour', color: '#2f7cf6' }, eyes: 'shades', shadeColor: '#111', mouth: 'grin', top: { style: 'vest', color: '#e53935' }, sleeves: 'short', bottom: { style: 'speedo', color: '#1e40af' }, shoes: '#666', bigArms: true },
    s1: { type: 'proj', name: 'Strong Right', elem: 'metal', sprite: 'fist', art: 'rocketfist', artK: 2.4, dmg: 85, speed: 14, r: 34 },
    s2: { type: 'upper', style: 'rocket', name: 'Coup de Burst', elem: 'fire', dmg: 85 },
    su: { type: 'beam', name: 'Radical Beam', elem: 'laser', power: 0.95 },
  },
  {
    id: 'brook', name: 'BROOK', full: 'Brook', group: 0, style: 'sword', elem: 'soul',
    quote: 'Yohohoho! Skull joke!',
    look: { skin: '#f5f5f5', scale: 1.15, build: 'slim', hair: { style: 'afro', color: '#111' }, hat: { type: 'tophat', color: '#111', color2: '#5a2a2a' }, eyes: 'skull', mouth: 'teeth', top: { style: 'suit', color: '#151515', color2: '#d81b60' }, sleeves: 'long', bottom: { style: 'pants', color: '#151515' }, shoes: '#111', weapon: 'cane' },
    s1: { type: 'proj', name: 'Soul Solid', elem: 'ice', sprite: 'slash', art: 'slash_ice', artK: 3.8, dmg: 70, speed: 12, r: 40 },
    s2: { type: 'rush', style: 'through', single: true, name: 'Humming Prelude: Arrow Notch Slash', elem: 'slash', dmg: 90 },
    su: { type: 'fubuki', name: 'Faint Song: Blizzard Slash', elem: 'ice' },
  },
  {
    id: 'jinbe', name: 'JINBE', full: 'Jinbe', group: 0, style: 'punch', elem: 'water',
    quote: 'The sea is my home. You never stood a chance!',
    look: { skin: '#4a7fc4', scale: 1.22, build: 'big', hair: { style: 'tied', color: '#1a1a1a' }, eyes: 'sharp', mouth: 'tusks', top: { style: 'kimono', color: '#f57c00', color2: '#1a237e' }, sleeves: 'long', bottom: { style: 'hakama', color: '#1a237e' }, shoes: '#222' },
    s1: { type: 'proj', name: 'Sprinkled Water Shot', elem: 'water', sprite: 'orb', art: 'watershot', artK: 2.6, dmg: 70, speed: 12, r: 30 },
    s2: { type: 'rush', style: 'drill', name: 'Vagabond Drill', elem: 'water', dmg: 90 },
    su: { type: 'bigproj', name: 'Five Thousand Tile Fist', elem: 'water', sprite: 'wave', art: 'waterfist', artK: 2.8, r: 95, speed: 7, power: 1.3 },
  },
  {
    id: 'akainu', name: 'AKAINU', full: 'Akainu', group: 1, style: 'punch', elem: 'magma',
    quote: 'Absolute justice!',
    look: { skin: '#e8b48a', scale: 1.15, build: 'big', hair: { style: 'short', color: '#1a1a1a' }, hat: { type: 'marine' }, eyes: 'sharp', mouth: 'calm', extras: ['rose'], top: { style: 'suit', color: '#b71c1c', color2: '#f8bbd0' }, sleeves: 'long', bottom: { style: 'pants', color: '#b71c1c' }, coat: { type: 'marine', color: '#f5f5f5' }, shoes: '#111' },
    s1: { type: 'proj', name: 'Hound Blaze', elem: 'magma', sprite: 'fireball', art: 'magmahound', artK: 2.3, dmg: 90, speed: 13, r: 50, hits: 2 },
    s2: { type: 'rush', style: 'erupt', name: 'Dark Dog', elem: 'magma', dmg: 100 },
    su: { type: 'rain', name: 'Meteor Volcano', elem: 'magma', art: 'magmafist', artK: 4.4, power: 1.15 },
  },
  {
    id: 'kizaru', name: 'KIZARU', full: 'Kizaru', group: 1, style: 'kick', elem: 'light',
    quote: 'Ohhh... so scary~',
    look: { skin: '#e8b48a', scale: 1.18, build: 'slim', hair: { style: 'curlyshort', color: '#2b2b2b' }, eyes: 'shades', shadeColor: '#5d4037', mouth: 'oo', top: { style: 'stripes', color: '#f2d03b', color2: '#c9a227' }, sleeves: 'long', bottom: { style: 'pants', color: '#f2d03b' }, coat: { type: 'marine', color: '#f5f5f5' }, shoes: '#fafafa' },
    s1: { type: 'beam', name: 'Heavenly Cloud Sword', elem: 'light', art: 'lightsword', dmg: 85 },
    s2: { type: 'teleport', name: 'Eight-Span Mirror', elem: 'light', dmg: 85 },
    su: { type: 'yasakani', name: 'Sacred Jewels of Light', elem: 'light' },
  },
  {
    id: 'aokiji', name: 'AOKIJI', full: 'Aokiji', group: 1, style: 'punch', elem: 'ice',
    quote: "Lazy justice... but I still won.",
    look: { skin: '#d9a273', scale: 1.28, build: 'slim', hair: { style: 'curly', color: '#1a1a1a' }, eyes: 'sleepy', mouth: 'calm', extras: ['sleepmask'], top: { style: 'vest3', color: '#f5f5f5', color2: '#2962ff' }, sleeves: 'long', sleeveColor: '#2962ff', bottom: { style: 'pants', color: '#f5f5f5' }, coat: { type: 'marine', color: '#f5f5f5' }, shoes: '#5d4037' },
    s1: { type: 'proj', name: 'Ice Block: Pheasant Beak', elem: 'ice', sprite: 'ice', art: 'icepheasant', artK: 2.4, dmg: 85, speed: 11, r: 50, hits: 2 },
    s2: { type: 'pillar', name: 'Ice Time', elem: 'ice', art: 'iceberg', dmg: 85 },
    su: { type: 'screen', name: 'Ice Age', elem: 'ice', finalFx: 'freeze', power: 0.85 },
  },
  {
    id: 'garp', name: 'GARP', full: 'Monkey D. Garp', group: 1, style: 'punch', elem: 'haki',
    quote: 'Fist of LOVE! Bwahahaha!',
    look: { skin: '#e8b48a', scale: 1.2, build: 'big', hair: { style: 'none', color: '#eee' }, hat: { type: 'doghat' }, eyes: 'normal', mouth: 'grin', extras: ['beardWhite', 'scarEye'], top: { style: 'suit', color: '#f5f5f5', color2: '#1e40af' }, sleeves: 'long', bottom: { style: 'pants', color: '#1e3a8a' }, coat: { type: 'marine', color: '#f5f5f5' }, shoes: '#111' },
    s1: { type: 'rush', style: 'bigpunch', name: 'Fist of Love', elem: 'haki', dmg: 100 },
    s2: { type: 'proj', name: 'Fist Bone Meteor', elem: 'punch', sprite: 'cannonball', art: 'cannonball', artK: 2.1, artSpin: 0.3, dmg: 90, speed: 13, r: 30, count: 3 },
    su: { type: 'galaxy', name: 'Galaxy Impact', elem: 'haki', power: 1.15 },
  },
  {
    id: 'smoker', name: 'SMOKER', full: 'Smoker', group: 1, style: 'sword', elem: 'smoke',
    quote: "You're not getting away from me!",
    look: { skin: '#f0c8a0', scale: 1.15, build: 'big', hair: { style: 'spiky', color: '#eceff1' }, eyes: 'sharp', mouth: 'calm', top: { style: 'openshirt', color: '#fafafa' }, sleeves: 'long', bottom: { style: 'pants', color: '#1e3a8a' }, coat: { type: 'fur', color: '#fafafa', color2: '#2e7d32' }, shoes: '#6d4c41', weapon: 'staff' },
    s1: { type: 'proj', name: 'White Blow', elem: 'smoke', sprite: 'orb', art: 'smokefist', artK: 3, dmg: 80, speed: 11, r: 40 },
    s2: { type: 'rush', name: 'White Launcher', elem: 'smoke', dmg: 90 },
    su: { type: 'pillar', name: 'White Out', elem: 'smoke', art: 'smoketrap' },
  },
  {
    id: 'ace', name: 'ACE', full: 'Portgas D. Ace', group: 2, style: 'punch', elem: 'fire',
    quote: 'Thanks for fighting me. That was fun!',
    look: { skin: '#f2c099', hair: { style: 'wavy', color: '#1a1a1a' }, hat: { type: 'cowboy', color: '#ef6c00' }, eyes: 'normal', mouth: 'smile', extras: ['freckles', 'beads'], top: { style: 'shirtless' }, sleeves: 'none', sash: '#5d4037', bottom: { style: 'shorts3', color: '#222' }, shoes: '#3e2723' },
    s1: { type: 'proj', name: 'Fire Fist', elem: 'fire', sprite: 'fireball', art: 'firefist', artK: 2.6, dmg: 75, speed: 12, r: 38, hits: 2 },
    s2: { type: 'upper', style: 'firepillar', name: 'Fire Pillar', elem: 'fire', dmg: 90 },
    su: { type: 'bigproj', name: 'Flame Emperor', elem: 'fire', sprite: 'sun', art: 'flamesun', artK: 2.8, r: 105, speed: 6, power: 1.25 },
  },
  {
    id: 'shanks', name: 'SHANKS', full: 'Red-Haired Shanks', group: 2, style: 'sword', elem: 'haki',
    quote: "Let's have a party!",
    look: { skin: '#f2c099', scale: 1.08, hair: { style: 'messy', color: '#c62828' }, eyes: 'normal', mouth: 'smile', extras: ['scars3', 'stubble'], top: { style: 'openshirt', color: '#fafafa' }, sleeves: 'long', sash: '#4e342e', bottom: { style: 'pants', color: '#8d6e63' }, coat: { type: 'cape', color: '#1a1a1a', color2: '#b71c1c' }, oneArm: true, shoes: '#3e2723', weapon: 'katana' },
    s1: { type: 'wave', name: 'Divine Departure', elem: 'haki', art: 'slash_haki', dmg: 80 },
    s2: { type: 'rush', style: 'hakiburst', name: "Conqueror's Haki Burst", elem: 'haki', dmg: 70 },
    su: { type: 'screen', name: "Conqueror's Haki", elem: 'haki', power: 0.85 },
  },
  {
    id: 'whitebeard', name: 'WHITEBEARD', full: 'Edward Newgate', group: 2, style: 'sword', elem: 'quake',
    quote: 'Gurarara! The One Piece is real!',
    look: { skin: '#f0b98a', scale: 1.55, build: 'big', hair: { style: 'none', color: '#eee' }, hat: { type: 'bandana', color: '#1a1a1a' }, eyes: 'sharp', mouth: 'calm', extras: ['mustacheWB'], top: { style: 'shirtless' }, sleeves: 'none', sash: '#1e3a8a', bottom: { style: 'pants', color: '#c8b37a' }, coat: { type: 'cape', color: '#f5f5f5', color2: '#f5f5f5' }, shoes: '#111', weapon: 'bisento' },
    s1: { type: 'wave', name: 'Sea Quake', elem: 'quake', art: 'quake', dmg: 85 },
    s2: { type: 'rush', style: 'shima', name: 'Island Shaker', elem: 'quake', dmg: 95 },
    su: { type: 'screen', name: 'Great Quake', elem: 'quake', art: 'quake', power: 0.9 },
  },
  {
    id: 'blackbeard', name: 'BLACKBEARD', full: 'Marshall D. Teach', group: 2, style: 'punch', elem: 'dark',
    quote: 'Zehahaha! Dreams never end!',
    look: { skin: '#d9a273', scale: 1.4, build: 'fat', hair: { style: 'curly', color: '#111' }, hat: { type: 'bandana', color: '#b71c1c' }, eyes: 'normal', mouth: 'bigrin', extras: ['beardBig'], top: { style: 'openshirt', color: '#fafafa' }, sleeves: 'long', sash: '#d32f2f', bottom: { style: 'pants', color: '#212121' }, coat: { type: 'cape', color: '#111', color2: '#4a148c' }, shoes: '#111' },
    s1: { type: 'rush', style: 'vortexpull', name: 'Black Vortex', elem: 'dark', dmg: 85 },
    s2: { type: 'rush', style: 'airquake', name: 'Quake Punch', elem: 'quake', dmg: 95 },
    su: { type: 'screen', name: 'Black Hole', elem: 'dark', art: 'blackhole', power: 0.9 },
  },
  {
    id: 'mihawk', name: 'MIHAWK', full: 'Dracule Mihawk', group: 2, style: 'sword', elem: 'slash',
    quote: 'Come back when you are stronger.',
    look: { skin: '#f2c099', scale: 1.1, hair: { style: 'slick', color: '#111' }, hat: { type: 'plume', color: '#111', color2: '#fafafa' }, eyes: 'hawk', mouth: 'calm', extras: ['mustacheThin', 'goatee', 'cross'], top: { style: 'suit', color: '#2a1a1a', color2: '#8d1b1b' }, sleeves: 'long', bottom: { style: 'pants', color: '#1a1a1a' }, coat: { type: 'cape', color: '#1a1a1a', color2: '#6d1b1b' }, shoes: '#111', weapon: 'yoru' },
    s1: { type: 'proj', name: 'Black Blade Slash', elem: 'slash', sprite: 'slash', art: 'slash_green', artK: 3.4, dmg: 80, speed: 14, r: 58 },
    s2: { type: 'rush', style: 'blink', name: 'Hawk Strike', elem: 'slash', dmg: 95 },
    su: { type: 'bigproj', spritePose: 'slashfinish', name: "World's Strongest Slash", elem: 'slash', sprite: 'slash', art: 'slash_green', artK: 2.8, r: 130, speed: 16, power: 1.2 },
  },
  {
    id: 'crocodile', name: 'CROCODILE', full: 'Sir Crocodile', group: 2, style: 'punch', elem: 'sand',
    quote: 'Dreams are for fools.',
    look: { skin: '#e8c4a0', scale: 1.2, build: 'big', hair: { style: 'slick', color: '#111' }, eyes: 'sharp', mouth: 'smirk', extras: ['scarNose'], top: { style: 'suit', color: '#7e5232', color2: '#ff9800' }, sleeves: 'long', bottom: { style: 'pants', color: '#3e2723' }, coat: { type: 'fur', color: '#212121', color2: '#6d4c41' }, hook: true, shoes: '#111' },
    s1: { type: 'wave', name: 'Desert Sword', elem: 'sand', dmg: 80 },
    s2: { type: 'proj', name: 'Sand Storm', elem: 'sand', sprite: 'tornado', art: 'sandstorm', artK: 4, dmg: 75, speed: 8, r: 46, hits: 3 },
    su: { type: 'pillar', name: 'Heavy Sand Storm', elem: 'sand', art: 'sandstorm' },
  },
  {
    id: 'doflamingo', name: 'DOFLAMINGO', full: 'Donquixote Doflamingo', group: 2, style: 'kick', elem: 'string',
    quote: 'Fufufu! Pirates are evil? Who decides that?',
    look: { skin: '#f0b98a', scale: 1.3, build: 'big', hair: { style: 'buzz', color: '#ffe082' }, eyes: 'shades', shadeColor: '#c62828', mouth: 'bigrin', top: { style: 'openshirt', color: '#fafafa' }, sleeves: 'long', bottom: { style: 'pants', color: '#ff8a50' }, coat: { type: 'feather', color: '#ff4fa0' }, shoes: '#fafafa' },
    s1: { type: 'beam', name: 'Overheat', elem: 'string', dmg: 80 },
    s2: { type: 'rush', style: 'pull', name: 'Parasite', elem: 'string', dmg: 70 },
    su: { type: 'screen', name: 'Birdcage', elem: 'string', power: 0.85 },
  },
  {
    id: 'kaido', name: 'KAIDO', full: 'Kaido', group: 2, style: 'sword', elem: 'fire',
    quote: "Ororo... that's all you've got?",
    look: { skin: '#e8b48a', scale: 1.7, build: 'big', hair: { style: 'longwild', color: '#1a1a1a' }, eyes: 'sharp', mouth: 'teeth', extras: ['horns', 'beardKaido'], top: { style: 'shirtless' }, sleeves: 'none', sash: '#fafafa', bottom: { style: 'hakama', color: '#eeeeee' }, coat: { type: 'cape', color: '#5e35b1', color2: '#311b92' }, shoes: '#3e2723', weapon: 'club' },
    s1: { type: 'beam', name: 'Bolo Breath', elem: 'fire', dmg: 90, big: 1.5 },
    s2: { type: 'pillar', name: 'Dragon Twister', elem: 'twister', dragon: true, dmg: 95 },
    su: { type: 'dragonform', name: 'Fish-Fish Fruit: Azure Dragon', elem: 'fire', power: 1.1 },
  },
  {
    id: 'bigmom', name: 'BIG MOM', full: 'Charlotte Linlin', group: 2, style: 'punch', elem: 'fire', companions: ['prometheus', 'zeus'],
    quote: 'Mamamama! Bring me sweets!',
    look: { skin: '#f7c99e', scale: 1.55, build: 'fat', hair: { style: 'pinkcurly', color: '#ff80ab' }, hat: { type: 'pirate', color: '#1a1a1a' }, eyes: 'fem', mouth: 'lips', top: { style: 'dress', color: '#f06292', color2: '#ffffff' }, sleeves: 'short', bottom: { style: 'skirt', color: '#f06292' }, coat: { type: 'cape', color: '#1a1a1a', color2: '#c62828' }, shoes: '#880e4f' },
    s1: { type: 'proj', name: 'Prometheus Fireball', elem: 'fire', sprite: 'fireball', art: 'flamesun', artK: 2.2, from: 'prometheus', dmg: 75, speed: 10, r: 46, hits: 2 },
    s2: { type: 'pillar', name: 'Zeus Thunder', elem: 'lightning', art: 'lightning', dmg: 90, from: 'zeus' },
    su: { type: 'mamaflame', name: 'Heavenly Fire & Zeus Thunder', elem: 'fire', power: 1.35 },
  },
  {
    id: 'law', name: 'LAW', full: 'Trafalgar Law', group: 2, style: 'sword', elem: 'room',
    quote: 'Room... Shambles. Operation complete.',
    look: { skin: '#e8b48a', scale: 1.08, build: 'slim', hair: { style: 'short', color: '#1a1a1a' }, hat: { type: 'furhat' }, eyes: 'tired', mouth: 'smirk', extras: ['goatee', 'earrings'], top: { style: 'hoodie', color: '#fbc02d', color2: '#111' }, sleeves: 'long', sleeveColor: '#111', bottom: { style: 'pants', color: '#d7ccc8' }, shoes: '#111', weapon: 'nodachi' },
    s1: { type: 'teleport', name: 'Shambles', elem: 'room', dmg: 85 },
    s2: { type: 'rush', style: 'pierce', name: 'Injection Shot', elem: 'room', dmg: 90 },
    su: { type: 'pillar', name: 'Gamma Knife', elem: 'room', knife: true },
  },
  {
    id: 'hancock', name: 'HANCOCK', full: 'Boa Hancock', group: 2, style: 'kick', elem: 'love',
    quote: 'Even if I win, I am still beautiful!',
    look: { skin: '#f7d2ad', scale: 1.05, build: 'slim', hair: { style: 'long', color: '#111', bangs: true }, eyes: 'fem', mouth: 'lips', extras: ['snakeEarrings'], top: { style: 'dress', color: '#c62828', color2: '#ffd54f' }, sleeves: 'long', bottom: { style: 'skirt', color: '#c62828' }, shoes: '#8d1b1b' },
    s1: { type: 'proj', name: 'Slave Arrow', elem: 'love', sprite: 'heart', art: 'heartarrow', artK: 2.2, dmg: 60, speed: 13, r: 22, count: 3 },
    s2: { type: 'upper', name: 'Perfume Femur', elem: 'love', dmg: 85 },
    su: { type: 'mellow', name: 'Love-Love Mellow', elem: 'love', finalFx: 'stone' },
  },
  {
    id: 'buggy', name: 'BUGGY', full: 'Buggy the Clown', group: 2, style: 'punch', elem: 'slash',
    quote: 'Gyahahaha! Bow before the flashy Captain Buggy!',
    look: { skin: '#f7d2ad', scale: 1.05, hair: { style: 'long', color: '#4fc3f7' }, hat: { type: 'pirate', color: '#fafafa' }, eyes: 'sharp', mouth: 'bigrin', top: { style: 'suit', color: '#fafafa', color2: '#43a047' }, sleeves: 'long', bottom: { style: 'pants', color: '#8d1b1b' }, coat: { type: 'cape', color: '#fafafa', color2: '#cfd8dc' }, shoes: '#6d4c41' },
    s1: { type: 'proj', name: 'Chop-Chop Cannon', elem: 'slash', sprite: 'orb', art: 'buggyhand', artK: 2.4, dmg: 75, speed: 13, r: 28 },
    s2: { type: 'wave', name: 'Chop-Chop Rice Cracker', elem: 'slash', art: 'buggysaw', dmg: 85, split: true },
    su: { type: 'dual', name: 'Chop-Chop Festival', maxName: 'Special Buggy Ball', elem: 'slash',
      lv1: { type: 'festival', elem: 'slash', power: 0.95 },
      max: { type: 'cannon', elem: 'fire', art: 'buggyball', artK: 2.3, r: 100, speed: 9, power: 1.2 } },
  },
  {
    id: 'marco', name: 'MARCO', full: 'Marco the Phoenix', group: 2, style: 'kick', elem: 'bluefire',
    quote: 'The phoenix always rises again, yoi.',
    look: { skin: '#f2c099', scale: 1.1, hair: { style: 'spiky', color: '#ffd54f' }, eyes: 'tired', mouth: 'calm', top: { style: 'openshirt', color: '#8e24aa' }, sleeves: 'long', sash: '#4fc3f7', bottom: { style: 'pants', color: '#1a237e' }, shoes: '#6d4c41' },
    s1: { type: 'proj', name: 'Bluebird', elem: 'bluefire', sprite: 'orb', art: 'bluebird', artK: 3, dmg: 75, speed: 12, r: 34 },
    s2: { type: 'rush', style: 'talon', name: 'Crane Talons', elem: 'bluefire', dmg: 95 },
    su: { type: 'beastform', name: 'Phoenix Brand', elem: 'bluefire', art: 'bluephoenix', artK: 2.2, power: 1.25 },
  },
  {
    id: 'sabo', name: 'SABO', full: 'Sabo', group: 2, style: 'sword', elem: 'fire',
    quote: 'Leave this to your big brother!',
    look: { skin: '#f7d2ad', hair: { style: 'short', color: '#ffd54f' }, hat: { type: 'pirate', color: '#1a1a1a' }, eyes: 'normal', mouth: 'grin', top: { style: 'suit', color: '#1a237e', color2: '#fafafa' }, sleeves: 'long', bottom: { style: 'pants', color: '#90a4ae' }, coat: { type: 'cape', color: '#1a1a1a', color2: '#263238' }, shoes: '#1a1a1a', weapon: 'staff' },
    s1: { type: 'rush', spritePose: 'special', name: 'Dragon Claw', elem: 'haki', dmg: 95 },
    s2: { type: 'wave', name: 'Dragon Breath', elem: 'quake', art: 'dragonbreath', dmg: 85 },
    su: { type: 'bigproj', spritePose: 'super', name: 'Flame Dragon King', elem: 'fire', sprite: 'fireball', art: 'firedragon', artK: 2.4, r: 120, speed: 9, power: 1.25 },
  },
  {
    id: 'yamato', name: 'YAMATO', full: 'Yamato', group: 2, style: 'sword', elem: 'ice',
    quote: 'I am Kozuki Oden!',
    look: { skin: '#f7d2ad', scale: 1.15, hair: { style: 'long', color: '#fafafa' }, eyes: 'fem', mouth: 'teeth', extras: ['horns'], top: { style: 'robe', color: '#fafafa', color2: '#b39ddb' }, sleeves: 'none', bottom: { style: 'hakama', color: '#d32f2f' }, shoes: '#8d6e63', weapon: 'club' },
    s1: { type: 'beam', name: 'Namuji Glacier Fang', elem: 'ice', art: 'icebreath', dmg: 85 },
    s2: { type: 'upper', name: 'Hallowed Glacier Slash', elem: 'ice', dmg: 90 },
    su: { type: 'pillar', name: 'Thunder Bagua', elem: 'lightning', art: 'baguabolt', power: 1.15 },
  },
  {
    id: 'arlong', name: 'ARLONG', full: 'Arlong', group: 2, style: 'sword', elem: 'water',
    quote: 'Shahahaha! Fish-men are the strongest!',
    look: { skin: '#9fa8ff', scale: 1.3, build: 'big', hair: { style: 'longwild', color: '#1a1a1a' }, hat: { type: 'furhat' }, eyes: 'sharp', mouth: 'teeth', top: { style: 'openshirt', color: '#fbc02d' }, sleeves: 'short', sash: '#9e9e9e', bottom: { style: 'pants', color: '#5d4037' }, shoes: '#6d4c41', weapon: 'katana' },
    s1: { type: 'rush', spritePose: 'special', name: 'Shark Darts', elem: 'water', dmg: 95 },
    s2: { type: 'proj', spritePose: 'super', name: 'Tooth Attack', elem: 'slash', sprite: 'orb', art: 'sharktooth', artK: 2.6, dmg: 80, speed: 15, r: 24 },
    su: { type: 'drill', name: 'Shark Tooth Drill', elem: 'water', power: 1.15 },
  },
  {
    id: 'kuma', name: 'KUMA', full: 'Bartholomew Kuma', group: 2, style: 'punch', elem: 'paw',
    quote: 'If you could take a trip, where would you go?',
    look: { skin: '#e8c4a0', scale: 1.5, build: 'fat', hair: { style: 'curlylong', color: '#1a1a1a' }, hat: { type: 'doghat' }, eyes: 'shades', shadeColor: '#cfd8dc', mouth: 'calm', top: { style: 'suit', color: '#1a1a1a', color2: '#fafafa' }, sleeves: 'long', bottom: { style: 'pants', color: '#bdbdbd' }, shoes: '#6d4c41' },
    s1: { type: 'proj', name: 'Pad Cannon', elem: 'paw', sprite: 'orb', art: 'pawcannon', artK: 2.6, dmg: 80, speed: 14, r: 36 },
    s2: { type: 'teleport', spritePose: 'special', name: 'Paw Travel', elem: 'paw', dmg: 80 },
    su: { type: 'ursa', name: 'Ursa Shock', elem: 'paw', power: 1.2 },
  },
  {
    id: 'enel', name: 'ENEL', full: 'Enel', group: 2, style: 'sword', elem: 'lightning',
    quote: 'Yahahaha! I am God!',
    look: { skin: '#f2c099', scale: 1.15, hair: { style: 'short', color: '#ffd54f' }, eyes: 'tired', mouth: 'calm', top: { style: 'shirtless' }, sleeves: 'none', sash: '#1e63c4', bottom: { style: 'pants', color: '#ff9800' }, shoes: '#f2c099', weapon: 'staff' },
    s1: { type: 'beam', name: 'Vari', elem: 'lightning', bolt: true, dmg: 80 },
    s2: { type: 'pillar', name: 'El Thor', elem: 'lightning', art: 'elthor', dmg: 90 },
    su: { type: 'dual', name: '200 Million Volt Amaru', maxName: 'Raigo', elem: 'lightning',
      lv1: { type: 'pillar', elem: 'lightning', art: 'amaru', power: 1.1 },
      max: { type: 'screen', elem: 'lightning', art: 'raigo', power: 1.0 } },
  },
];
const GROUPS = [
  { name: 'STRAW HATS', color: '#d32f2f' },
  { name: 'MARINES', color: '#1e63c4' },
  { name: 'OTHERS', color: '#7b1fa2' },
];

// arcade final boss (not selectable)
const BOSSES = [
  {
    id: 'imu', name: 'IMU', full: 'Imu', group: 2, style: 'sword', elem: 'dark', boss: true,
    quote: 'Ants can never stop me!',
    look: { skin: '#6d4c41', scale: 1.45, build: 'big', hair: { style: 'longwild', color: '#f5f5f5' }, eyes: 'sharp', mouth: 'smirk', extras: ['horns'], top: { style: 'shirtless' }, sleeves: 'none', sash: '#fbc02d', bottom: { style: 'pants', color: '#212121' }, coat: { type: 'cape', color: '#111', color2: '#b71c1c' }, shoes: '#111', weapon: 'nodachi' },
    // Stigma: a sentient Omen fireball marks the target, a bell tolls, the weapon Stigma falls on it
    s1: { type: 'proj', name: 'Stigma', elem: 'dark', sprite: 'fireball', art: 'omenorb', artK: 2.6, dmg: 95, speed: 9, r: 30, count: 1, stigma: true },
    // Nemesis: a blade of Omen flame shoots out of the crossguard and impales
    s2: { type: 'beam', name: 'Nemesis', elem: 'dark', art: 'nemesis', dmg: 95, big: 1.1 },
    // Honebami Toshiro: the sword's Omen serpents with demonic heads lunge; Lv3 adds the Mother Flame from the sky
    su: { type: 'honebami', name: 'Honebami Toshiro', maxName: 'Mother Flame', elem: 'dark', power: 1.2 },
  },
];
const charById = id => ROSTER.find(c => c.id === id) || BOSSES.find(c => c.id === id);
